
<?php
 require_once("inc/dbcall.php");
  //var dataString = 'name=' + tusername + '&pwd=' + pwd + '&fname=' + fname + '&memail=' + temail
  // + '&tspecialty=' + tspecialty + '&utype=' + $usertype;
$db = new Db();
//get user submitted values
$name = $_POST['name'];
$pwd = $db->makepwd($_POST['pwd']);
$eorgname = $_POST['eorgname'];
$etype = $_POST['etype'];
$eemail = $_POST['eemail'];
$emobileno = $_POST['emobileno'];
$utype = $_POST['utype'];
//end of member data
$sql="INSERT INTO `users` (`username`, `password`, `eorgname`, `etype`, `email`, `mobileno`, `address`, `usertype`)
VALUES ('$name' ,'$pwd', '$eorgname', '$etype', '$eemail', '$emobileno', 'no', '$utype')";
$db->query($sql);
//get last inserted user id
$userid = $db->getUserID();

//get the user id generated by db ,to insret into speciality table
$sql = "INSERT INTO `usrspeciality` (`etype`, `users_idusers`)
VALUES ('$etype', $userid)";
$db->query($sql);
